# Generated by Django 4.2.11 on 2024-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('DESTINATION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CITY_ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=50)),
                ('TYPE', models.CharField(choices=[('food', '음식'), ('sights', '관광지'), ('cafe', '카페')], max_length=100)),
                ('CONTENT', models.CharField(max_length=1000)),
                ('FEATURE', models.CharField(max_length=1000)),
                ('LATITUDE', models.FloatField()),
                ('LONGITUDE', models.FloatField()),
                ('IMG_URL', models.CharField(default='img', max_length=100)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
    ]
